---
title: "Quick Analysis of Inital ONT LMGSeq Influenza Test Runs "
output: html_notebook
---

#Influenza Experimental Coinfections ONT LMGSeq Test Runs Analysis
*Started Sept 11, 2026

## Goals
We have two (actually three) test runs where we have run the new ONT-LMGSeq primers on the MinION with flu coinfections. We had three goals with those test runs.

1. Verify that LMGSeq in its ONT iteration works as planned for known coinfections (data quality and reassortment)
2. Examine whether lower concentrations of RT can be used.
3. Determine if we can reconfirm triple reassortants

## Data

Three ONT runs:
1. CA09xPAN99 Coinfection: One full run that
2. Triple/Quad Coinfection (includes 2 doubles, one triple, and one quad)
3. Concentration Test

## Approach
We'll start with CA09xPAN99 full run. It provides the simplest case where we don't have to deal with other data, it's just one run, one coinfection. Let's keep it relatively high level and get stats overall for sequencing and demultiplexing. If it looks reasoable on the demultiplexing side (meaning reads per plate/well), don't spend too much effort on that. A quick fix that might be necessary is just using cross2. Probably a major focus is going to be the database matching.

### Environment Set up

```{bash}
ssh sldmunoz@franklin.hpc.ucdavis.edu

#Load conda as a module
module load conda/base

#Slurm interactive
srun -c 1 -t 12:00:00 --mem=10000 --pty /bin/bash
#This job is just to set up data and working directories

#Navigate to the lab group directory
cd /group/sldmunozgrp

#Get to the working directory that Courtney set up for me
cd /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025
```

#### CA09/PAN99 Coinfection Analysis 

Now we start to look into. First let's get to the results with the pipeline as is (as of Sept 11, 2026)

What is the working directory for this run?
```{bash}
cd /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/CA09xPAN99_102325
```

The source FASTQ is `CA09xPAN99_calls_2025-12-17_T21-10-01.fastq`. Let's start there and see how many reads we are working with

```{bash}
#Number of reads in the main FASTQ
wc -l CA09xPAN99_calls_2025-12-17_T21-10-01.fastq | awk '{print $2 " , " $1/4}'
#CA09xPAN99_calls_2025-12-17_T21-10-01.fastq , 3524782
```

Okay so 3,524,782 or 3.5M reads roughly. Which by the way, seems very low. Next we will look at the reads remaining after each step.

```{bash}
#Reads after Porechop
wc -l porechop_outputs/CA09xPAN99_calls_2025-12-17_T21-10-01_porechop.fastq | awk '{print $2 " , " $1/4}'
#porechop_outputs/CA09xPAN99_calls_2025-12-17_T21-10-01_porechop.fastq , 5686122
#Note, these could end up being *more* reads because of read splitting. 
#Indeed way more! 5,686,122 roughly 5.7M reads. Seems like a lot? 

#Reads after Cutadapt Plate Demultiplexing
less plate_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.log
#Reads with adapters:                 3,962,030 (69.7%)
#Looks like only finding 69% 

#Examining more closely looks like plate02 was trimmed 3,959,814, or 3959814/3962030 = 0.9994407 over 99.94% of trimmed reads were plate 2, so that's great

#Quick note that of those plate02 reads, 2440777 or (2440777/3959814=0.6163868) 61.39% of them were reverse complements, which is more or less in line with what we expect

#Reads after Cutadapt Well demultiplexing
#The script output a file with number of demultiplexed reads per plate/well
less read_counts_demultiplexed_CA09xPAN99.txt

#A visual inspection has most of the reads in plate02 wells mostly singletons in other 


```

Had Claude make me a custom script to summarize the demultiplexing stats (after PoreChop/Cutadapt). That file is `cutadapt_demultiplexing_stats_qc.R`

Also downloaded the `read_counts_demultiplexed_CA09xPAN99.txt` file to `outputs`.

Here's some results:
Plate 2 has 2,849,010 reads. Which is more than any cross in the 2023 paper (mean reads / cross = 968,866 reads, range 219,326–1,544,248)

Within plate 2 here's what it looks like for the wells:
  n_wells mean_reads sd_reads min_reads max_reads
    <int>      <dbl>    <dbl>     <int>     <int>
1      96     29677.   38017.         3    167498

Some wells are really low, but on average that's 29,677 reads per sample, which is *plenty*. Looks like from the 2023 paper the average reads per well are 10,570, if I'm reading the code right (not in the paper). So again more, which makes sense, but not as much as you would think given that I only have only one cross for the whole flow cell.

Also have quite a few wells, 22, that seemingly dropped off

`plate02: 22 well(s) with reads < 1% of plate mean (possible failed wells): well12, well24, well33, well35, well36, well46, well47, well48, well55, well58, well59, well60, well66, well71, well72, well77, well81, well82, well83, well84, well95, well96`

```{bash}
#Reads after usearch Strain Assignment


```

Need to loop back to detail the findings, but bascially the reassortment rate is much lower, but in general the segment with the most reaasortment is NS and NP, though way less. The segment representation plot with reassortants only, actually looks comparable to the earlier plot (albeit to the all plot).

*Sept 12, 2026*

The thing that is sticking out to me is how many reads in the well are going unmatched by usearch (come to think of it, this should be in the quality control measures). Want to check the matches, the databases, and don't forget the amplicon, i.e. does it have ONT landing pad, uni regions, etc?  

My approach will be to sandbox this within the working folder and examine them carefully 

Asked Claude to find a well supported parental and a reassortant sample that is well supported, ideally at multiple segments, but that still has a lot of reads unassigned. So I'll be working with:
Parental:     plate02_well17
Reassortant:  plate02_well75   

```{bash}
#Get into working directory
cd /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/CA09xPAN99_102325/

#Where is the YML?
#Can't find it, so going to go off the output headers to find the versions

#My starting point is going to be the demultiplexed (from cutadapt) FASTQ's so let's get those and put them in a subfolder of the main working folder
mkdir /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/sam_analyses/
cd /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/sam_analyses/

#Starting with plate02_well75 our reassortant representative
cp /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/CA09xPAN99_102325/cutadapt_outputs/plate02/well75/plate02_well75_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq .

#Let's create an environment 
conda create -n longread_lmgseq_temp python=3.12.11 cutadapt=5.2 usearch=11.0.667

#Got it, now activate
conda activate longread_lmgseq_temp 

#First thing is to inspect the fastq - I especially want to get a sense of whether DelVGs are playing a role here
less plate02_well75_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq

#Going to look at read length distributions, with a couple of scripts provided by Claude

#Length summary stats
awk 'NR%4==2 {print length($0)}' plate02_well75_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq | sort -n | awk '{a[NR]=$1; sum+=$1} END {print "n="NR, "min="a[1], "max="a[NR], "mean="sum/NR, "median="a[int(NR/2)]}'
#n=8121 min=0 max=4270 mean=196.558 median=4
#Median is weird

#Read length distribution
awk 'NR%4==2 {print length($0)}' plate02_well75_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq | sort -n | uniq -c | awk '{print $2"\t"$1}' > plate_02_well75_demux_fastq_read_length_distribution.txt

#Okay confirmed, lots of reads at 4bp. Not good obviously. Not many polymerase reads. Let's do the same for the parental representative read (see separate section below)

#Now looking at how well formed these amplicons are, using code I made from Ile's projects
#Are there landing pads here?
#First get rid of ONT landing pad
cutadapt -a TTTCTGTTGGTGCTGATATTG...GAAGATAGAGCGACAGGCAAGT -a ACTTGCCTGTCGCTCTATCTTC...CAATATCAGCACCAACAGAAA -o plate02_well75_ont_landing_pad.fastq plate02_well75_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq --untrimmed-output=plate02_well75_ont_landing_pad_untrimmed.fastq --action=lowercase > plate02_well75_ont_landing_pad.txt
#0.4% of reads with adapters. Most of these were very short, adapter-only reads, so I'll call it pretty close to the zero I got in the other test sample.

#Now let's check for the uni primers
cutadapt -a AGCAAAAGCAGG...CCTTGTTTCTACT -a AGTAGAAACAAGG...CCTGCTTTTGC -o plate02_well75_uni.fastq plate02_well75_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq --untrimmed-output=plate02_well75_uni_untrimmed.fastq --action=lowercase > plate02_well75_uni.txt
#This looks just ok 
#Total reads processed:                   8,121
#Reads with adapters:                     3,626 (44.6%)

less plate02_well75_uni.fastq
#At least looks like it trimmed where it should

#Now let's actually trim
cutadapt -a AGCAAAAGCAGG...CCTTGTTTCTACT -a AGTAGAAACAAGG...CCTGCTTTTGC -o final_plate02_well75_uni.fastq plate02_well75_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq --discard-untrimmed > final_plate02_well75_uni.txt

less final_plate02_well75_uni.txt
#Same as before, as expected

#Now usearch
usearch -usearch_global final_plate02_well75_uni.fastq -db CA09_PAN99.fasta -id 0.90 -blast6out plate02_well75_corrected_db_90.b6 -strand both -top_hit_only
#00:05 50Mb    100.0% Searching, 43.9% matched
#Only 44% matched

#Let's summarize
cut -f 2 plate02_well75_corrected_db_90.b6 | cut -d , -f 1 | sort | uniq -c | \
awk '{
  n = $1; strain_seg = $2
  split(strain_seg, a, "_"); locus = a[2]
  total[locus] += n
  if (n > max[locus]) { max[locus] = n; best[locus] = strain_seg }
}
END {
  OFS = "\t"
  for (loc in best) printf "%s\t%d\t%d\t%.4f\n", best[loc], max[loc], total[loc], max[loc]/total[loc]
}' | sort -k2,2 -nr
#CA09_NS	  845	908	0.9306
#PAN99_M	  458	463	0.9892
#PAN99_HA	  173	173	1.0000
#PAN99_PB1	23	23	1.0000
#PAN99_NA	  11	13	0.8462
#PAN99_NP	  10	10	1.0000
#PAN99_PA	  2	2	1.0000


### plate02_well17 ###

cd /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/sam_analyses/

#Now plate02_well17 our parental representative
cp /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/CA09xPAN99_102325/cutadapt_outputs/plate02/well17/plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq .

#First thing is to inspect the fastq - I especially want to get a sense of whether DelVGs are playing a role here
less plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq

#Going to look at read length distributions, with a couple of scripts provided by Claude

#Length summary stats
awk 'NR%4==2 {print length($0)}' plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq | sort -n | awk '{a[NR]=$1; sum+=$1} END {print "n="NR, "min="a[1], "max="a[NR], "mean="sum/NR, "median="a[int(NR/2)]}'
#n=167498 min=3 max=6078 mean=1030.91 median=1005
#Ok, this looks more reasoable

#Read length distribution
awk 'NR%4==2 {print length($0)}' plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq | sort -n | uniq -c | awk '{print $2"\t"$1}' > plate02_well17_demux_fastq_read_length_distribution.txt

#This looks *way* more reasonable, clear peaks where the full length segments should be. Notably the suspected DelVG peaks are pretty clear. I am more curious now about these very long reads, one 6kb!!

#Going to check with a Claude-made oneliner
awk 'NR%4==2{if(length($0)>maxlen){maxlen=length($0);seq=$0}}END{print seq}' plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq

#Hard to conclude here with just less or BLAST, lets move on

#Now looking at how well formed these amplicons are, using code I made from Ile's projects

#Are there landing pads here?
#First get rid of ONT landing pad
cutadapt -a TTTCTGTTGGTGCTGATATTG...GAAGATAGAGCGACAGGCAAGT -a ACTTGCCTGTCGCTCTATCTTC...CAATATCAGCACCAACAGAAA -o plate02_well17_ont_landing_pad.fastq plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq --untrimmed-output=plate02_well17_ont_landing_pad_untrimmed.fastq --action=lowercase > plate02_well17_ont_landing_pad.txt
#Zero, so I will assume they have been taken off

#Now let's check for the uni primers
cutadapt -a AGCAAAAGCAGG...CCTTGTTTCTACT -a AGTAGAAACAAGG...CCTGCTTTTGC -o plate02_well17_uni.fastq plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq --untrimmed-output=plate02_well17_uni_untrimmed.fastq --action=lowercase > plate02_well17_uni.txt
#This looks great!
#Total reads processed:                 167,498
#Reads with adapters:                   165,932 (99.1%)

#Sequence: AGTAGAAACAAGG...CCTGCTTTTGC; Type: linked; Length: 13+11; 5' trimmed: 156368 times; 3' trimmed: 152905 times
#Interestingly way more Adapter 2 trimmed, did the reads get reverse complemented in the upstream script?

#Peeking at the untrimmed
less plate02_well17_uni_untrimmed.fastq
#Looks like a lot of good reads there. Blasted a couple of them and they are in fact complete reads. Many but not all have an rc label

#Visual inspection of the lowercase... looks really clean. At the end and beginning
less plate02_well17_uni.fastq

#What happened to the longest read?
awk 'NR%4==2{if(length($0)>maxlen){maxlen=length($0);seq=$0}}END{print seq}' plate02_well17_uni.fastq
#It obliterated the read on the F side leaving a fragment that matches to H3N2 NS (HK and PAN99 included)

#Now let's actually trim
cutadapt -a AGCAAAAGCAGG...CCTTGTTTCTACT -a AGTAGAAACAAGG...CCTGCTTTTGC -o final_plate02_well17_uni.fastq plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq --discard-untrimmed > final_plate02_well17_uni.txt

less final_plate02_well17_uni.txt
#Total basepairs processed:   172,674,772 bp
#Total written (filtered):    166,901,534 bp (96.7%)
#Looks great, and seems like keeping most of the length of reads, consitent with uni trimming at the ends

#Finally, down to the usearching. Let's go!!

#First let's find the database and copy 
cd /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/sam_analyses/
cp /group/sldmunozgrp/cysto_LMGSeq08-25/sam_basecalled_flu_2025/CA09xPAN99_102325/genotyping_outputs/CA09_PAN99_CA09_PAN99.fasta .

#Interesting that everything was copied twice. Let's keep as is and then see if that has an effect
usearch -usearch_global final_plate02_well17_uni.fastq -db CA09_PAN99_CA09_PAN99.fasta -id 0.90 -blast6out plate02_well17_orig_database_90_merged.b6 -strand both -top_hit_only
#Super slow... Interesting. But pretty high percentage match right off the bat
#09:23 120Mb   100.0% Searching, 81.6% matched

#Ended up at 81.6%, which I think is way higher than before (EDIT: Or was it?)
less plate02_well17_orig_database_90_merged.b6
#Looks actually really, really good.

#Now let's look at the summary
#Will need to piece it together
#Using part of the one-liner
cut -f 2 plate02_well17_orig_database_90_merged.b6 | cut -d , -f 1 | sort | uniq -c | sort -nr 
#Not complete, asking Claude for a one-liner
cut -f 2 plate02_well17_orig_database_90_merged.b6 | cut -d , -f 1 | sort | uniq -c | \
awk '{
  n = $1; strain_seg = $2
  split(strain_seg, a, "_"); locus = a[2]
  total[locus] += n
  if (n > max[locus]) { max[locus] = n; best[locus] = strain_seg }
}
END {
  OFS = "\t"
  for (loc in best) printf "%s\t%d\t%d\t%.4f\n", best[loc], max[loc], total[loc], max[loc]/total[loc]
}' | sort -k2,2 -nr
#PAN99_NS	49944	49950	0.9999
#PAN99_M	45945	45950	0.9999
#PAN99_NP	15851	15852	0.9999
#PAN99_NA	15026	15026	1.0000
#PAN99_HA	5635	5635	1.0000
#PAN99_PA	1104	1105	0.9991
#PAN99_PB1	1007	1008	0.9990
#PAN99_PB2	832	832	1.0000


#Directly compare whether the uni trimming did anything to the assignment rate. So now not uni trimmed FASTQ
usearch -usearch_global plate02_well17_CA09xPAN99_calls_2025-12-17_T21-10-01_cutadapt_porechop.fastq -db CA09_PAN99_CA09_PAN99.fasta -id 0.90 -blast6out plate02_well17_orig_database_90_merged.b6 -strand both -top_hit_only
#09:32 133Mb   100.0% Searching, 81.2% matchedpected 1600:58 118Mb    10.2% Searching, 82.1% matched
#Yeah maybe a tiny bit. 81.6% and 82.1%

#My guess is that when I change the duplicates in the database that it will be quicker assignment. Let's check
#Fix database
cp CA09_PAN99_CA09_PAN99.fasta CA09_PAN99.fasta

#Remove duplicates, 
vi CA09_PAN99.fasta

#Same command, just changing the database and the output names
usearch -usearch_global final_plate02_well17_uni.fastq -db CA09_PAN99.fasta -id 0.90 -blast6out plate02_well17_corrected_db_90.b6 -strand both -top_hit_only
#07:44 55Mb    100.0% Searching, 81.6% matched
#Actually does not look faster, really. But moving forward with this, because it is the right thing


cut -f 2 plate02_well17_corrected_db_90.b6 | cut -d , -f 1 | sort | uniq -c | \
awk '{
  n = $1; strain_seg = $2
  split(strain_seg, a, "_"); locus = a[2]
  total[locus] += n
  if (n > max[locus]) { max[locus] = n; best[locus] = strain_seg }
}
END {
  OFS = "\t"
  for (loc in best) printf "%s\t%d\t%d\t%.4f\n", best[loc], max[loc], total[loc], max[loc]/total[loc]
}' | sort -k2,2 -nr
#PAN99_NS	49944	49950	0.9999
#PAN99_M	45945	45950	0.9999
#PAN99_NP	15851	15852	0.9999
#PAN99_NA	15026	15026	1.0000
#PAN99_HA	5635	5635	1.0000
#PAN99_PA	1104	1105	0.9991
#PAN99_PB1	1007	1008	0.9990
#PAN99_PB2	832	832	1.0000

```

OK, hanging it up for now, but here are a few things to do when I pick this up again:
1. Change the filenames to reflect the database and uni trimming changes
2. Play around with the thresholds pid and the global/local matching. Is there a way I can get unmatched
3. Once I increase the percentage, scale to the rest of the wells and check results in R

*September 14, 2026*

Some takeaways after chat with Courtney during check-in. First, the uni12/13 primer trimming didn't really do much. In the end, the. The duplication of the genomes in the reference database didn't affect much either. Maybe two things to follow-up on is the loss of reads at the cutadapt stage (only 69.7%), but still plenty of reads to work with and the all reads being in one orientation after uni12/13 trimming.  

Courtney's recommendation was to look at the database first and I agree.

*September 15, 2026*

Focus today is going to be checking the database and adjusting to see the results. My main hypothesis is that CA09 isn't matching well at all. However, I am only somewhat certain that plate02_well07 is pure PAN99, don't have an equivalent for CA09. 

```{bash}
#First let's make individual databases for CA09 and PAN99. Grep. Actually, need to remove the wrap from the FASTA first

#PAN99
awk 'BEGIN {RS=">";FS="\n"} NR>1 {seq=""; for (i=2;i<=NF;i++) seq=seq$i; print ">"$1"\n"seq}' CA09_PAN99.fasta | grep -A 1 "PAN99" > PAN99.fasta

#CA09
awk 'BEGIN {RS=">";FS="\n"} NR>1 {seq=""; for (i=2;i<=NF;i++) seq=seq$i; print ">"$1"\n"seq}' CA09_PAN99.fasta | grep -A 1 "CA09" > CA09.fasta

#Now let's try to align
```

Asked Claudio to make a script to align reads with minimap2

```{bash}
#!/bin/bash
# Map presumed-pure PAN99 reads to the PAN99 reference and build a new
# consensus, one sequence per segment.

READS="final_plate02_well17_uni.fastq"
REF="PAN99.fasta"
OUT_PREFIX="PAN99_well17_consensus"
MIN_DEPTH=5

minimap2 -ax map-ont "$REF" "$READS" > "${OUT_PREFIX}.sam"
samtools sort -o "${OUT_PREFIX}.sorted.bam" "${OUT_PREFIX}.sam"
samtools index "${OUT_PREFIX}.sorted.bam"

samtools flagstat "${OUT_PREFIX}.sorted.bam"
samtools idxstats "${OUT_PREFIX}.sorted.bam"

samtools consensus --min-depth "$MIN_DEPTH" -o "${OUT_PREFIX}.fasta" "${OUT_PREFIX}.sorted.bam"

# Count Ns per segment in the new consensus
awk '/^>/{if(seq) print name, gsub(/N/,"N",seq); name=$0; seq=""; next} {seq=seq $0} END{if(seq) print name, gsub(/N/,"N",seq)}' "${OUT_PREFIX}.fasta"
```

Saved to a script

```{bash}
 vi consensus.sh
 #Copy pasted
 
chmod +x consensus.sh
./consensus.sh
#[M::mm_idx_gen::0.002*13.08] collected minimizers
#[M::mm_idx_gen::0.003*9.74] sorted minimizers
#[M::main::0.003*9.69] loaded/built the index for 8 target sequence(s)
#[M::mm_mapopt_update::0.003*9.28] mid_occ = 10
#[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 8
#[M::mm_idx_stat::0.003*8.96] distinct minimizers: 2473 (100.00% are singletons); average occurrences: 1.000; average #spacing: 5.408; total length: 13373
#[M::worker_pipeline::40.605*1.00] mapped 165932 sequences
#[M::main] Version: 2.31-r1302
#[M::main] CMD: minimap2 -ax map-ont PAN99.fasta final_plate02_well17_uni.fastq
#[M::main] Real time: 40.607 sec; CPU: 40.631 sec; Peak RSS: 0.393 GB
#188422 + 0 in total (QC-passed reads + QC-failed reads)
#165932 + 0 primary
#1 + 0 secondary
#22489 + 0 supplementary
#0 + 0 duplicates
#0 + 0 primary duplicates
#188057 + 0 mapped (99.81% : N/A)
#165567 + 0 primary mapped (99.78% : N/A)
#0 + 0 paired in sequencing
#0 + 0 read1
#0 + 0 read2
#0 + 0 properly paired (N/A : N/A)
#0 + 0 with itself and mate mapped
#0 + 0 singletons (N/A : N/A)
#0 + 0 with mate mapped to a different chr
#0 + 0 with mate mapped to a different chr (mapQ>=5)
#PAN99_PB1	2311	41648	0
#PAN99_HA	1731	5789	0
#PAN99_M	999	48879	0
#PAN99_NS	857	52187	0
#PAN99_NA	1436	16482	0
#PAN99_PA	2192	1837	0
#PAN99_PB2	2310	3479	0
#PAN99_NP	1537	17756	0
#*	0	0	365
#>PAN99_PB1 0
#>PAN99_HA 0
#>PAN99_M 0
#>PAN99_NS 0
#>PAN99_NA 0
#>PAN99_PA 0
#>PAN99_PB2 1
#>PAN99_NP 0
```

Asked Claudio to compare the FASTA's and I got this
"The reference is nearly perfect for 7 of 8 segments: PB2, PB1, PA, NP, M are all byte-for-byte identical. NA has a single SNP at position 940. NS has a single difference that turns out to be a non-issue (the reference has an IUPAC ambiguity code R (A/G) at position 427; the consensus called it as A — not a real variant at all). PB2 has one N at position 1124, which is the single low-depth position from the --min-depth 5 call we discussed."
(Note: another model had HA polymorphisms at 9 but got blocked)

"From the well17 comparison: minimap2 mapped 99.81% of reads (99.78% primary) to PAN99, vs. usearch matched 81.6% against the same well's reads. That's a gap of about 18 percentage points."

Next, asked Claudio how to extend the consensus beyond the reference and it turns out that there's software designed by CDC: IRMA. For now, just using a quick python script Claudio generated.

Script by Claudio: extend_consensus_ends.py
```{bash}
#!/usr/bin/env python3
"""
Recover well-supported read sequence that extends beyond the reference's
5' and 3' boundaries, and splice it onto an existing samtools-consensus fasta.

Why this is needed: minimap2 soft-clips any part of a read that would extend
past the reference's coordinate system. That clipped sequence is still in the
BAM (in the read's SEQ field), but samtools consensus / mpileup-based tools
only build consensus within reference coordinates, so they never see it.

Approach:
1. For each segment (reference contig), find reads whose alignment starts
   at reference position 0 (candidates for a 5' overhang) or ends at the
   segment's last position (candidates for a 3' overhang).
2. Pull each such read's soft-clipped bases at that specific end.
3. Require a minimum number of reads agreeing before trusting an overhang
   (same spirit as --min-depth on the reference-guided consensus).
4. Build a consensus of the overhang sequences with spoa (a reference-free,
   partial-order-alignment consensus tool -- no reference needed since these
   sequences have no coordinate system to align to).
5. Prepend/append the overhang consensus to the existing per-segment
   consensus sequence.

Requirements:
    pip install pysam spoa --break-system-packages
    (spoa also exists as a standalone CLI via bioconda if the python
    bindings aren't available in your environment)

Usage:
    python3 extend_consensus_ends.py \\
        --bam PAN99_well17_consensus.sorted.bam \\
        --consensus PAN99_well17_consensus.fasta \\
        --out PAN99_well17_consensus_extended.fasta \\
        --min-support 5
"""

import argparse
import subprocess
import sys

import pysam
from Bio import SeqIO


def get_end_overhangs(bam_path, contig, contig_len):
    """Return (left_overhangs, right_overhangs): lists of soft-clipped
    sequence from reads whose alignment abuts the contig's start/end."""
    left_overhangs = []
    right_overhangs = []

    bam = pysam.AlignmentFile(bam_path, "rb")
    for read in bam.fetch(contig):
        if read.is_unmapped or read.is_secondary or read.is_supplementary:
            continue  # keep this simple -- primary alignments only
        cigar = read.cigartuples
        if not cigar:
            continue

        # CIGAR ops relative to the reference: 4 = soft clip (S)
        # A left overhang requires: alignment starts at ref position 0
        # AND the CIGAR actually begins with a soft clip (i.e. there was
        # something to clip, not just a read that happens to start there).
        if read.reference_start == 0 and cigar[0][0] == 4:
            clip_len = cigar[0][1]
            if clip_len > 0:
                left_overhangs.append(read.query_sequence[:clip_len])

        # A right overhang requires: alignment ends at the last ref base
        # AND the CIGAR ends with a soft clip.
        if read.reference_end == contig_len and cigar[-1][0] == 4:
            clip_len = cigar[-1][1]
            if clip_len > 0:
                right_overhangs.append(read.query_sequence[-clip_len:])

    bam.close()
    return left_overhangs, right_overhangs


def spoa_consensus(sequences, tmp_prefix):
    """Run spoa on a list of sequences with no reference, return consensus string.
    Falls back to None if there's nothing usable to align."""
    if not sequences:
        return None

    fasta_path = f"{tmp_prefix}.fasta"
    with open(fasta_path, "w") as f:
        for i, seq in enumerate(sequences):
            f.write(f">read_{i}\n{seq}\n")

    # -r 0 : output consensus only (no MSA)
    result = subprocess.run(
        ["spoa", "-r", "0", fasta_path],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  spoa failed on {fasta_path}: {result.stderr}", file=sys.stderr)
        return None

    lines = result.stdout.strip().splitlines()
    # spoa's consensus output is a single fasta record; sequence is everything
    # after the header line
    seq_lines = [l for l in lines if not l.startswith(">")]
    return "".join(seq_lines) if seq_lines else None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bam", required=True, help="Sorted, indexed BAM used to build the consensus")
    ap.add_argument("--consensus", required=True, help="Existing per-segment consensus fasta to extend")
    ap.add_argument("--out", required=True, help="Output fasta with extended segments")
    ap.add_argument("--min-support", type=int, default=5,
                     help="Minimum number of reads agreeing on an overhang before trusting it (default 5, matching your consensus min-depth)")
    ap.add_argument("--max-overhang", type=int, default=150,
                     help="Maximum allowed per-read soft-clip length to be included in overhang consensus "
                          "(default 150). Reads with clips longer than this are almost certainly artifacts "
                          "(cross-segment reads, chimeras) rather than genuine terminal sequence. "
                          "Expected real overhangs from influenza A terminal NCRs are ~13-80 nt; "
                          "anything in the hundreds is a red flag. After filtering, if fewer than "
                          "--min-support reads remain the overhang is not extended.")
    args = ap.parse_args()

    consensus_records = {r.id: str(r.seq) for r in SeqIO.parse(args.consensus, "fasta")}
    bam = pysam.AlignmentFile(args.bam, "rb")
    contig_lengths = dict(zip(bam.references, bam.lengths))
    bam.close()

    out_records = []
    for contig, seq in consensus_records.items():
        if contig not in contig_lengths:
            print(f"WARNING: {contig} not found in BAM header, leaving unchanged", file=sys.stderr)
            out_records.append((contig, seq))
            continue

        contig_len = contig_lengths[contig]
        left_overhangs, right_overhangs = get_end_overhangs(args.bam, contig, contig_len)

        print(f"{contig}: {len(left_overhangs)} reads with a 5' overhang, "
              f"{len(right_overhangs)} reads with a 3' overhang")

        left_ext = ""
        right_ext = ""

        # Filter overhangs by --max-overhang before trusting them.
        # Long soft-clips (hundreds of nt) are almost always reads that only
        # partially aligned to this segment (cross-segment homology, chimeric
        # reads, etc.) rather than genuine terminal sequence recovery.
        def filter_and_report(overhangs, end_label):
            all_lens = sorted(len(s) for s in overhangs)
            kept = [s for s in overhangs if len(s) <= args.max_overhang]
            dropped = len(overhangs) - len(kept)
            if dropped:
                print(f"  {end_label}: {dropped} read(s) dropped (clip > {args.max_overhang} nt); "
                      f"lengths before filter: {all_lens[:20]}{'...' if len(all_lens)>20 else ''}")
            return kept

        left_filtered  = filter_and_report(left_overhangs,  "5' filter")
        right_filtered = filter_and_report(right_overhangs, "3' filter")

        if len(left_filtered) >= args.min_support:
            lengths = sorted(len(s) for s in left_filtered)
            print(f"  5' overhang lengths after filter (sorted): {lengths}")
            left_ext = spoa_consensus(left_filtered, f"/tmp/{contig}_left") or ""
            if left_ext:
                print(f"  -> recovered {len(left_ext)} nt on the 5' end: {left_ext}")
        elif left_overhangs:
            print(f"  5': {len(left_filtered)} read(s) remain after length filter "
                  f"(< --min-support {args.min_support}) -- not extending")

        if len(right_filtered) >= args.min_support:
            lengths = sorted(len(s) for s in right_filtered)
            print(f"  3' overhang lengths after filter (sorted): {lengths}")
            right_ext = spoa_consensus(right_filtered, f"/tmp/{contig}_right") or ""
            if right_ext:
                print(f"  -> recovered {len(right_ext)} nt on the 3' end: {right_ext}")
        elif right_overhangs:
            print(f"  3': {len(right_filtered)} read(s) remain after length filter "
                  f"(< --min-support {args.min_support}) -- not extending")

        out_records.append((contig, left_ext + seq + right_ext))

    with open(args.out, "w") as f:
        for header, seq in out_records:
            f.write(f">{header}\n")
            for i in range(0, len(seq), 70):
                f.write(seq[i:i+70] + "\n")

    print(f"\nWrote extended consensus to {args.out}")


if __name__ == "__main__":
    main()```

Command to run the script:

```{bash}
#First prepare the environment. Using conda instead of pip
conda install -c bioconda -c conda-forge pysam biopython spoa

python3 extend_consensus_ends.py \
    --bam PAN99_well17_consensus.sorted.bam \
    --consensus PAN99_well17_consensus.fasta \
    --out PAN99_well17_consensus_extended_v3.fasta \
    --min-support 5 \
    --max-overhang 80
```

Ok finally, segments have been extended to a reasonable length. Here's the summary from Claudio

End	Range across 8 segments
5′ left	15–54 nt
3′ right	19–34 nt

Now going to use these new references in the usearch
```{bash}
#First, I want to do the new consensus with no extension
usearch -usearch_global final_plate02_well17_uni.fastq -db PAN99_well17_consensus.fasta -id 0.90 -blast6out plate02_well17_new_consensus_db_global_90.b6 -strand both -top_hit_only
#Ugh, seems to be very similar
#Yep :(
#04:46 51Mb    100.0% Searching, 81.6% matched

#Taking a peek
cut -f 2,3,4 plate02_well17_new_consensus_db_global_90.b6 | less

#Let's look at the summary
cut -f 2 plate02_well17_new_consensus_db_global_90.b6 | cut -d , -f 1 | sort | uniq -c | \
awk '{
  n = $1; strain_seg = $2
  split(strain_seg, a, "_"); locus = a[2]
  total[locus] += n
  if (n > max[locus]) { max[locus] = n; best[locus] = strain_seg }
}
END {
  OFS = "\t"
  for (loc in best) printf "%s\t%d\t%d\t%.4f\n", best[loc], max[loc], total[loc], max[loc]/total[loc]
}' | sort -k2,2 -nr
#PAN99_NS	49945	49945	1.0000
#PAN99_M	45945	45945	1.0000
#PAN99_NP	15851	15851	1.0000
#PAN99_NA	15035	15035	1.0000
#PAN99_HA	5646	5646	1.0000
#PAN99_PA	1104	1104	1.0000
#PAN99_PB1	1008	1008	1.0000
#PAN99_PB2	832	832	1.0000

#Pretty much same as before


#Let's try local with the new consensus with no extension. So same as above, just local
usearch -usearch_local final_plate02_well17_uni.fastq -db PAN99_well17_consensus.fasta -id 0.90 -blast6out plate02_well17_new_consensus_db_local_90.b6 -strand both -top_hit_only
#Even from the get-go seems like this works better 100% matching. Not faster, though.

#Let's take a look
cut -f 2,3,4 plate02_well17_new_consensus_db_local_90.b6 | less

#Let's sort by match length
#Plenty of long matches, even though local alignment 
cut -f 2,3,4 plate02_well17_new_consensus_db_local_90.b6 | sort -k 3,3 -nr | less

#Summary
cut -f 2 plate02_well17_new_consensus_db_local_90.b6 | cut -d , -f 1 | sort | uniq -c | \
awk '{
  n = $1; strain_seg = $2
  split(strain_seg, a, "_"); locus = a[2]
  total[locus] += n
  if (n > max[locus]) { max[locus] = n; best[locus] = strain_seg }
}
END {
  OFS = "\t"
  for (loc in best) printf "%s\t%d\t%d\t%.4f\n", best[loc], max[loc], total[loc], max[loc]/total[loc]
}' | sort -k2,2 -nr
#PAN99_NS	51336	51336	1.0000
#PAN99_M	47849	47849	1.0000
#PAN99_PB1	22674	22674	1.0000
#PAN99_NP	17239	17239	1.0000
#PAN99_NA	15925	15925	1.0000
#PAN99_HA	6177	6177	1.0000
#PAN99_PB2	2694	2694	1.0000
#PAN99_PA	2011	2011	1.0000

#Now going to check the extended reference
#First, I want to do the new consensus extended

#First Global
usearch -usearch_global final_plate02_well17_uni.fastq -db PAN99_well17_consensus_extended_v3.fasta -id 0.90 -blast6out plate02_well17_new_consensus_extended_db_global_90.b6 -strand both -top_hit_only

#05:28 52Mb    100.0% Searching, 81.4% matched
#Looks pretty similar

#Summary
cut -f 2 plate02_well17_new_consensus_extended_db_global_90.b6 | cut -d , -f 1 | sort | uniq -c | \
awk '{
  n = $1; strain_seg = $2
  split(strain_seg, a, "_"); locus = a[2]
  total[locus] += n
  if (n > max[locus]) { max[locus] = n; best[locus] = strain_seg }
}
END {
  OFS = "\t"
  for (loc in best) printf "%s\t%d\t%d\t%.4f\n", best[loc], max[loc], total[loc], max[loc]/total[loc]
}' | sort -k2,2 -nr
#PAN99_NS	49740	49740	1.0000
#PAN99_M	45883	45883	1.0000
#PAN99_NP	15809	15809	1.0000
#PAN99_NA	15023	15023	1.0000
#PAN99_HA	5641	5641	1.0000
#PAN99_PA	1102	1102	1.0000
#PAN99_PB1	1005	1005	1.0000
#PAN99_PB2	829	829	1.0000

#Roughly similar to other global

#Second local
usearch -usearch_local final_plate02_well17_uni.fastq -db PAN99_well17_consensus_extended_v3.fasta -id 0.90 -blast6out plate02_well17_new_consensus_extended_db_local_90.b6 -strand both -top_hit_only

cut -f 2 plate02_well17_new_consensus_extended_db_local_90.b6 | cut -d , -f 1 | sort | uniq -c | \
awk '{
  n = $1; strain_seg = $2
  split(strain_seg, a, "_"); locus = a[2]
  total[locus] += n
  if (n > max[locus]) { max[locus] = n; best[locus] = strain_seg }
}
END {
  OFS = "\t"
  for (loc in best) printf "%s\t%d\t%d\t%.4f\n", best[loc], max[loc], total[loc], max[loc]/total[loc]
}' | sort -k2,2 -nr
#PAN99_NS	51295	51295	1.0000
#PAN99_M	47857	47857	1.0000
#PAN99_PB1	22716	22716	1.0000
#PAN99_NP	17237	17237	1.0000
#PAN99_NA	15928	15928	1.0000
#PAN99_HA	6169	6169	1.0000
#PAN99_PB2	2680	2680	1.0000
#PAN99_PA	2023	2023	1.0000

```

Okay, PAN99 seems to be just fine thank you very much. 
Only thing left to investigate which reads makes the gap between the 82ish% and 100%. 

Alignment
Alignment length looks great, seems like local will try to do the longest match possible. Flagging some very short 12nt matches - we probably need a cutoff. Curious if local alignment is picking up DelVGs - this probably would be a solid match on one side and a second half (roughly) of the read will be unmatched - don't know if usearch will do matches on each end.

ALSO: Check the extended reference to see if it gets better

Next steps:
1. Get a CA09 consensus
2. Test as above
3. Then make a new reference with both new references and run global and local

```{bash}

```

